config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts do
    resources :comments
  end
  get '/sign_in', to: 'users#sign_in'
  post '/sign_in', to: 'users#sign_in!'
  get '/sign_up', to: 'users#sign_up'
  post '/sign_up', to: 'users#sign_up!'
  get '/sign_out', to: 'users#sign_out'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if session[:user_id]
      @user = User.find(session[:user_id])
      return @user
    else
      return nil
    end
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find_by(post_id: params[:post_id])
  end

  def update
  end

  def destroy
    @comment = Comment.find_by(post_id: params[:post_id])
    @comment.destroy
    @post = Post.find(params[:post_id])
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:user_name, :datetime, :comment)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)

    redirect_to post_path(@post)
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :image_url,:datetime,:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_up
  end

  def sign_up!
    user = User.new(username: params[:username], password_digest: params[:password])
    if params[:password_confirmation] != params[:password]
      message = "Your passwords don't match!"
    elsif user.save
      message = "Your account has been created!"
    else
      message = "Your account couldn't be created. Did you enter a unique username and password?"
    end
    puts message
    redirect_to action: :sign_in
  end

  def sign_in
  end

  def sign_in!
    @user = User.find_by(username: params[:username])
    if !@user
      message = "This user doesn't exist!"
    elsif @user.password_digest != params[:password]
      message = "Your password's wrong!"
    else
      session[:user_id] = @user.id
      message = "You're signed in, #{@user.username}!"
    end
    puts message
    redirect_to root_url
  end

  def sign_out
    session[:user_id] = nil
    puts "You're signed out!"
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/comments/_comment.html.erb
<h1>THIS SHOULD BE A COMMENT</h1>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

  <%= f.label :user_name, "User Name" %>
  <%= f.text_field :user_name %>

  <%= f.label :datetime, "Date" %>
  <%= f.text_field :datetime %>

  <%= f.label :comment %>
  <%= f.text_field :comment %>

  <%= f.submit %>

<% end  %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>
<%= form_for [@post, @comment] do |f| %>

  <%= f.label :user_name, "User Name" %>
  <%= f.text_field :user_name %>

  <%= f.label :datetime, "Date" %>
  <%= f.text_field :datetime %>

  <%= f.label :comment %>
  <%= f.text_field :comment %>

  <%= f.submit %>

<% end  %>

<!-- Delete Comment -->
<%= form_for [@post, @comment], method: :delete do |f| %>
  <%= f.submit "Delete Comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scribbles</title>
  <meta charset="utf-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <h1 class="title">SCRIBBLES</h1>
  <nav>
    <a href="/sign_in">Sign in</a>
    <a href="/sign_up">Sign up</a>
    <a href="/sign_out">Sign out</a>
  </nav>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :image_url, "Image URL" %>
  <%= f.text_field :image_url %>

  <%= f.label :datetime, "Date Posted" %>
  <%= f.text_field :datetime %>

  <%= f.label :content, "Post" %>
  <%= f.text_field :content %>

  <%= f.submit %>

<% end  %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render partial: "form" %>

<%= form_for @post, method: :delete do |f| %>
  <%= f.submit "Delete Post!" %>
<% end %>

app/views/posts/index.html.erb
<h1>View All Posts</h1>
<ul>
<% @posts.each do |post|%>
<li>
  <%= link_to post.title, post %>
</li>
<% end %>
</ul>
<button><%=link_to "New Post", new_post_path%></button>

app/views/posts/new.html.erb
<h1>Create New Post</h1>

<%= render partial: "form" %>

<button><%=link_to "Cancel", posts_path%></button>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h2><%= @post.datetime %></h2>
<%= puts "*" * 90 %>
<%= puts @post.datetime %>
<img src="<%= @post.image_url %>" />
<article><%= simple_format(@post.content, {}, :sanitize => false) %></article>


<!-- Show comments -->
<div>
  <% @post.comments.each do |comment| %>
  <div class="username">
    <%= comment.user_name %>
  </div>
    <p><%= comment.comment %></p>
    <%=link_to "Edit Comment", edit_post_comment_path(@post,comment)%>
  <%end%>
</div>
<%= render partial: "comments/form" %>

app/views/users/sign_in.html.erb
<h2>Sign in</h2>
<%= form_tag("/sign_in", method: "post") do %>
  <input type="text" name="username" placeholder="username" />
  <input type="password" name="password" placeholder="password" />
  <input type="submit" value="Sign in" />
<% end %>

app/views/users/sign_up.html.erb
<h2>Sign up</h2>
<%= form_tag("/sign_up", method: "post") do %>
  <input type="text" name="username" placeholder="username" />
  <input type="password" name="password" placeholder="password" />
  <input type="password" name="password_confirmation" placeholder="password again" />
  <input type="submit" value="Sign up" />
<% end %>